AWSTemplateFormatVersion: '2010-09-09'
Transform: AWS::Serverless-2016-10-31
Description: >
  dynamodb-demo
  the usage for dynamodb

Resources:
  WorkTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DynamoDB-Demo-WorkTable
      AttributeDefinitions:
        - AttributeName: userId
          AttributeType: S
        - AttributeName: date
          AttributeType: S
        - AttributeName: yearMonth
          AttributeType: S
        - AttributeName: break
          AttributeType: N
      KeySchema:
        - AttributeName: userId
          KeyType: HASH
        - AttributeName: date
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: BreakIndex
          KeySchema:
            - AttributeName: yearMonth
              KeyType: HASH
            - AttributeName: break
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
  RensyuTable:
    Type: AWS::DynamoDB::Table
    Properties:
      TableName: DynamoDB-Demo-RensyuTable
      AttributeDefinitions:
        - AttributeName: pk
          AttributeType: S
        - AttributeName: sk
          AttributeType: S
        - AttributeName: departmentId
          AttributeType: S
      KeySchema:
        - AttributeName: pk
          KeyType: HASH
        - AttributeName: sk
          KeyType: RANGE
      BillingMode: PAY_PER_REQUEST
      GlobalSecondaryIndexes:
        - IndexName: DepartmentIndex
          KeySchema:
            - AttributeName: departmentId
              KeyType: HASH
            - AttributeName: pk
              KeyType: RANGE
          Projection:
            ProjectionType: ALL
